#Globals
source: .
destination: ./_site
layouts_dir: ./_layouts
collection: null
owner: Ilphrin
title: Ilphrin Freelance Web Designer
description: Freelance Web designer and Mozillian, passionned for Open-Source, UX, Metal, and Photography
url: https://www.ilphrin.com
plugins: ['jekyll-paginate', 'jekyll-timeago', 'jekyll-multiple-languages-plugin']
languages: ["en", "fr"]
exclude_from_localizations: ["js", "bower_components", "node_modules", "css", 'images', 'fonts', 'package.json', 'planet_feed.xml', 'robots.txt', 'staticman.yml']
exclude: [_css, _js, _images, _sass, package.json, package-lock.json]
baseurl: ""
excerpt_separator: "<!--break-->"
email: 'ilphrin@autistici.org'
social:
  twitter: 'https://twitter.com/Kilphrin'
  github: 'http://github.com/Ilphrin/'
  linkedin-square: 'https://www.linkedin.com/in/kevin-pellet-5a123ba9/edit/topcard/'
  flickr: 'https://www.flickr.com/photos/159186107@N06/'


#Handling reading
encoding: "utf-8"
markdown_ext: "markdown"
paginate_path: kevin/page/:num

#Conversion
highlighters: rouge
lsi: false

#Serving
port: 4001

#Backwards compatibility
relative_permalinks: false

#Outputting
permalink: date


#Markdown processors
maruku:
  png_engine: blahtex
  png_dir: images/latex
  png_url: /images/latex
  fenced_code_blocks: true

#SASS configuration

mermaid:
  src: "http://www.sveido.com/mermaid/dist/mermaid.full.js"

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "feeds.xml"
    - "feed.xml"
    - "node_modules/"
    - "fonts/"
    - "css/"
    - "js/"
    - "planet_feed.xml"

sass:
  style: compressed
