#Globals
source: .
destination: ./_site
plugins: ./_plugins
layouts: ./_layouts
collection: null
name: Kevin / Ilphrin
description: A blog about IT, free software and stuff like that
url: http://ilphrin.com

#Handling reading
encoding: "utf-8"
markdown_ext: "markdown"
paginate_path: kevin/page/:num

#Conversion
highlighters: rouge
lsi: false
paginate: 5

#Serving
detach: true
port: 4001

#Backwards compatibility
relative_permalinks: false

#Outputting
permalink: date
timezone:

#Markdown processors
maruku:
  png_engine: blahtex
  png_dir: images/latex
  png_url: /images/latex
  fenced_code_blocks: true
