#Globals
source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
collection: null
name: Kevin / Ilphrin
description: A blog about IT, free software and stuff like that
url: https://www.ilphrin.com
gems: ['jekyll-paginate', 'jekyll-mermaid', 'jekyll-multiple-languages-plugin']
languages: ["fr", "en"]
exclude_from_localizations: ["js", "bower_components", "node_modules", "css"]
exclude: [
  'Gruntfile.js',
  'new_article.sh'
]

#Handling reading
encoding: "utf-8"
markdown_ext: "markdown"
paginate_path: kevin/page/:num

#Conversion
highlighters: rouge
lsi: false
paginate: 5

#Serving
detach: true
port: 4001

#Backwards compatibility
relative_permalinks: false

#Outputting
permalink: date

#Markdown processors
maruku:
  png_engine: blahtex
  png_dir: images/latex
  png_url: /images/latex
  fenced_code_blocks: true

#SASS configuration
sass:
  style: compressed

mermaid:
  src: "http://www.sveido.com/mermaid/dist/mermaid.full.js"

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "feeds.xml"
    - "planet_feed.xml"
  include_posts:
    - "/kevin/index.html"
